// This file is generated by Prismic local builder. Update with care!

export { default as FeaturedLinks } from './FeaturedLinks'
export { default as QuestionAnswer } from './QuestionAnswer'
export { default as TextSection } from './TextSection'
